apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: qxzr35jku-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/qxzr35jku-dotnet-basic-gitops